/**
 * Local Everkinetic stills. The phone shows these even when the public
 * storage object is missing. CC BY-SA 3.0, credited on About.
 */
export const BUNDLED_EXERCISE_STILLS: Record<string, number> = {
  ab_wheel_rollout: require('../../../assets/exercise-stills/ab_wheel_rollout.webp'),
  arnold_press: require('../../../assets/exercise-stills/arnold_press.webp'),
  barbell_bench_press: require('../../../assets/exercise-stills/barbell_bench_press.webp'),
  barbell_curl: require('../../../assets/exercise-stills/barbell_curl.webp'),
  barbell_row: require('../../../assets/exercise-stills/barbell_row.webp'),
  bench_dips: require('../../../assets/exercise-stills/bench_dips.webp'),
  cable_chest_flyes: require('../../../assets/exercise-stills/cable_chest_flyes.webp'),
  cable_curl: require('../../../assets/exercise-stills/cable_curl.webp'),
  cable_hammer_curl: require('../../../assets/exercise-stills/cable_hammer_curl.webp'),
  cable_overhead_extension: require('../../../assets/exercise-stills/cable_overhead_extension.webp'),
  cable_pulldown_wide: require('../../../assets/exercise-stills/cable_pulldown_wide.webp'),
  cable_row: require('../../../assets/exercise-stills/cable_row.webp'),
  calf_raises: require('../../../assets/exercise-stills/calf_raises.webp'),
  chin_ups: require('../../../assets/exercise-stills/chin_ups.webp'),
  close_grip_bench_press: require('../../../assets/exercise-stills/close_grip_bench_press.webp'),
  close_grip_pulldown: require('../../../assets/exercise-stills/close_grip_pulldown.webp'),
  concentration_curl: require('../../../assets/exercise-stills/concentration_curl.webp'),
  deadlift: require('../../../assets/exercise-stills/deadlift.webp'),
  decline_bench_press: require('../../../assets/exercise-stills/decline_bench_press.webp'),
  dips_assisted: require('../../../assets/exercise-stills/dips_assisted.webp'),
  dumbbell_bench_press: require('../../../assets/exercise-stills/dumbbell_bench_press.webp'),
  dumbbell_curl: require('../../../assets/exercise-stills/dumbbell_curl.webp'),
  dumbbell_flyes: require('../../../assets/exercise-stills/dumbbell_flyes.webp'),
  dumbbell_shoulder_press: require('../../../assets/exercise-stills/dumbbell_shoulder_press.webp'),
  front_raises: require('../../../assets/exercise-stills/front_raises.webp'),
  front_squat: require('../../../assets/exercise-stills/front_squat.webp'),
  good_mornings: require('../../../assets/exercise-stills/good_mornings.webp'),
  hack_squat: require('../../../assets/exercise-stills/hack_squat.webp'),
  hammer_curl: require('../../../assets/exercise-stills/hammer_curl.webp'),
  hip_adduction: require('../../../assets/exercise-stills/hip_adduction.webp'),
  incline_bench_press: require('../../../assets/exercise-stills/incline_bench_press.webp'),
  lat_pulldown: require('../../../assets/exercise-stills/lat_pulldown.webp'),
  lateral_raises: require('../../../assets/exercise-stills/lateral_raises.webp'),
  leg_curls: require('../../../assets/exercise-stills/leg_curls.webp'),
  leg_extensions: require('../../../assets/exercise-stills/leg_extensions.webp'),
  leg_press: require('../../../assets/exercise-stills/leg_press.webp'),
  lunges: require('../../../assets/exercise-stills/lunges.webp'),
  overhead_press: require('../../../assets/exercise-stills/overhead_press.webp'),
  overhead_squat: require('../../../assets/exercise-stills/overhead_squat.webp'),
  overhead_tricep_extension: require('../../../assets/exercise-stills/overhead_tricep_extension.webp'),
  preacher_curl: require('../../../assets/exercise-stills/preacher_curl.webp'),
  push_ups: require('../../../assets/exercise-stills/push_ups.webp'),
  rear_delt_flyes: require('../../../assets/exercise-stills/rear_delt_flyes.webp'),
  reverse_lunges: require('../../../assets/exercise-stills/reverse_lunges.webp'),
  rope_tricep_pushdown: require('../../../assets/exercise-stills/rope_tricep_pushdown.webp'),
  seated_calf_raise: require('../../../assets/exercise-stills/seated_calf_raise.webp'),
  shrugs: require('../../../assets/exercise-stills/shrugs.webp'),
  side_plank: require('../../../assets/exercise-stills/side_plank.webp'),
  skull_crushers: require('../../../assets/exercise-stills/skull_crushers.webp'),
  spider_curl: require('../../../assets/exercise-stills/spider_curl.webp'),
  squat: require('../../../assets/exercise-stills/squat.webp'),
  step_ups: require('../../../assets/exercise-stills/step_ups.webp'),
  straight_arm_pulldown: require('../../../assets/exercise-stills/straight_arm_pulldown.webp'),
  t_bar_row: require('../../../assets/exercise-stills/t_bar_row.webp'),
  tricep_dips: require('../../../assets/exercise-stills/tricep_dips.webp'),
  tricep_pushdown: require('../../../assets/exercise-stills/tricep_pushdown.webp'),
  upright_row: require('../../../assets/exercise-stills/upright_row.webp'),
  weighted_dips: require('../../../assets/exercise-stills/weighted_dips.webp'),
};

export function bundledExerciseStill(exerciseId: string): number | null {
  return BUNDLED_EXERCISE_STILLS[exerciseId] ?? null;
}
