/**
 * One-shot generator for governed med catalog batch 1 (mental health + sleep/sedation focus).
 * Run: node scripts/generateMedCatalogBatch1.mjs
 * Writes: app/src/data/medCatalog.batch1.json
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(__dirname, '..', 'src', 'data', 'medCatalog.batch1.json');

const SN =
  'Reclaim MedicationKnowledge V1 batch 1 seed; high-level medication-class overview for educational context in-app.';
const SAFETY = 'Educational only. Not medical advice. Discuss changes with your clinician.';

const moodSleep = ['mood_relevant', 'sleep_relevant'];
const moodAnx = ['mood_relevant', 'anxiety_context'];
const moodAnxSleep = ['mood_relevant', 'anxiety_context', 'sleep_relevant'];
const stimFx = ['activation_relevant', 'sleep_relevant', 'mood_relevant'];
const sedFx = ['sedation_relevant', 'sleep_relevant', 'mood_relevant'];
const apFx = ['sedation_relevant', 'mood_relevant', 'fatigue_relevant'];

const stMS = ['mood_context', 'sleep_interpretation', 'fatigue_context'];
const stAnx = ['mood_context', 'anxiety_interpretation', 'sleep_interpretation'];
const stStim = ['mood_context', 'training_readiness', 'sleep_interpretation'];
const stBenzo = ['anxiety_interpretation', 'sleep_interpretation', 'fatigue_context'];
const stAP = ['mood_context', 'fatigue_context', 'sleep_interpretation'];

function entry({
  id,
  genericName,
  brandNames = [],
  matchAliases = [],
  category,
  medicationClass,
  mechanism,
  confidence = 0.78,
  effectTags,
  stateImpactTags,
  whatYouMightNotice = [
    'Responses vary between individuals; effects often emerge gradually when used for mood.',
    'Timing and formulation can influence daytime alertness and nighttime sleep.',
  ],
}) {
  return {
    id,
    genericName,
    brandNames,
    ...(matchAliases.length ? { matchAliases } : {}),
    category,
    medicationClass,
    activeIngredients: [genericName],
    mechanism,
    whatYouMightNotice,
    confidence,
    safetyNote: SAFETY,
    sourceNote: SN,
    effectTags,
    stateImpactTags,
  };
}

const rows = [
  entry({
    id: 'paroxetine',
    genericName: 'Paroxetine',
    brandNames: ['Paxil', 'Pexeva'],
    category: 'ssri',
    medicationClass: 'SSRI',
    mechanism:
      'Increases serotonin signaling in the brain, which may support mood and anxiety symptom patterns over time.',
    confidence: 0.84,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'citalopram',
    genericName: 'Citalopram',
    brandNames: ['Celexa'],
    category: 'ssri',
    medicationClass: 'SSRI',
    mechanism: 'Raises serotonin activity, which may help stabilize mood and anxiety symptoms with gradual onset.',
    confidence: 0.84,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'fluvoxamine',
    genericName: 'Fluvoxamine',
    brandNames: ['Luvox'],
    category: 'ssri',
    medicationClass: 'SSRI',
    mechanism: 'Serotonin reuptake inhibition; may support obsessive-compulsive and anxiety-related patterns when prescribed.',
    confidence: 0.8,
    effectTags: moodAnxSleep,
    stateImpactTags: stAnx,
  }),
  entry({
    id: 'vilazodone',
    genericName: 'Vilazodone',
    brandNames: ['Viibryd'],
    category: 'ssri',
    medicationClass: 'SSRI with partial agonist activity',
    mechanism: 'Combines serotonin reuptake effects with receptor modulation; mood effects often build over weeks.',
    confidence: 0.76,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'vortioxetine',
    genericName: 'Vortioxetine',
    brandNames: ['Trintellix'],
    category: 'ssri',
    medicationClass: 'Multimodal antidepressant',
    mechanism: 'Affects serotonin pathways through several mechanisms; may support mood and cognitive energy patterns in some people.',
    confidence: 0.76,
    effectTags: [...moodSleep, 'fatigue_relevant'],
    stateImpactTags: stMS,
  }),
  entry({
    id: 'desvenlafaxine',
    genericName: 'Desvenlafaxine',
    brandNames: ['Pristiq'],
    category: 'snri',
    medicationClass: 'SNRI',
    mechanism: 'Modulates serotonin and norepinephrine; may influence mood, energy, and physical symptom perception.',
    confidence: 0.82,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'levomilnacipran',
    genericName: 'Levomilnacipran',
    brandNames: ['Fetzima'],
    category: 'snri',
    medicationClass: 'SNRI',
    mechanism: 'SNRI activity that may affect mood, energy, and pain-related symptom interpretation over time.',
    confidence: 0.75,
    effectTags: [...moodSleep, 'pain_masking_relevant'],
    stateImpactTags: [...stMS, 'pain_perception'],
  }),
  entry({
    id: 'milnacipran',
    genericName: 'Milnacipran',
    brandNames: ['Savella'],
    category: 'snri',
    medicationClass: 'SNRI',
    mechanism: 'Norepinephrine and serotonin modulation; sometimes used in fibromyalgia-related care plans.',
    confidence: 0.74,
    effectTags: [...moodSleep, 'fatigue_relevant', 'pain_masking_relevant'],
    stateImpactTags: [...stMS, 'recovery_interpretation'],
  }),
  entry({
    id: 'amitriptyline',
    genericName: 'Amitriptyline',
    brandNames: ['Elavil'],
    category: 'tricyclic',
    medicationClass: 'Tricyclic antidepressant',
    mechanism: 'Affects several neurotransmitter systems; can be sedating and may influence sleep architecture.',
    confidence: 0.78,
    effectTags: sedFx,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'nortriptyline',
    genericName: 'Nortriptyline',
    brandNames: ['Pamelor'],
    category: 'tricyclic',
    medicationClass: 'Tricyclic antidepressant',
    mechanism: 'Similar family to other tricyclics; may support mood with somewhat less sedation for some individuals.',
    confidence: 0.77,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'imipramine',
    genericName: 'Imipramine',
    brandNames: ['Tofranil'],
    category: 'tricyclic',
    medicationClass: 'Tricyclic antidepressant',
    mechanism: 'Older antidepressant class with multiple receptor effects; sedation and dry mouth patterns are common.',
    confidence: 0.75,
    effectTags: sedFx,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'desipramine',
    genericName: 'Desipramine',
    brandNames: ['Norpramin'],
    category: 'tricyclic',
    medicationClass: 'Tricyclic antidepressant',
    mechanism: 'Tricyclic antidepressant that may influence mood and energy with variable sedation.',
    confidence: 0.74,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'clomipramine',
    genericName: 'Clomipramine',
    brandNames: ['Anafranil'],
    category: 'tricyclic',
    medicationClass: 'Tricyclic antidepressant',
    mechanism: 'Serotonin-rich tricyclic sometimes used in obsessive-compulsive symptom patterns.',
    confidence: 0.76,
    effectTags: moodAnxSleep,
    stateImpactTags: stAnx,
  }),
  entry({
    id: 'doxepin',
    genericName: 'Doxepin',
    brandNames: ['Sinequan'],
    category: 'tricyclic',
    medicationClass: 'Tricyclic antidepressant',
    mechanism: 'Sedating tricyclic; sometimes used for sleep support or depression depending on dose and formulation.',
    confidence: 0.76,
    effectTags: sedFx,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'alprazolam',
    genericName: 'Alprazolam',
    brandNames: ['Xanax'],
    category: 'benzodiazepine',
    medicationClass: 'Benzodiazepine',
    mechanism: 'Enhances calming neurotransmitter signaling; fast onset among benzodiazepines with sedation potential.',
    confidence: 0.78,
    effectTags: sedFx,
    stateImpactTags: stBenzo,
  }),
  entry({
    id: 'lorazepam',
    genericName: 'Lorazepam',
    brandNames: ['Ativan'],
    category: 'benzodiazepine',
    medicationClass: 'Benzodiazepine',
    mechanism: 'Short-to-intermediate calming effects that may reduce acute anxiety symptoms and sedation.',
    confidence: 0.78,
    effectTags: sedFx,
    stateImpactTags: stBenzo,
  }),
  entry({
    id: 'clonazepam',
    genericName: 'Clonazepam',
    brandNames: ['Klonopin'],
    category: 'benzodiazepine',
    medicationClass: 'Benzodiazepine',
    mechanism: 'Longer-acting benzodiazepine sometimes used for panic or seizure-related plans.',
    confidence: 0.77,
    effectTags: sedFx,
    stateImpactTags: stBenzo,
  }),
  entry({
    id: 'diazepam',
    genericName: 'Diazepam',
    brandNames: ['Valium'],
    category: 'benzodiazepine',
    medicationClass: 'Benzodiazepine',
    mechanism: 'Classic benzodiazepine with muscle-relaxant qualities for some people and sedation.',
    confidence: 0.77,
    effectTags: sedFx,
    stateImpactTags: stBenzo,
  }),
  entry({
    id: 'chlordiazepoxide',
    genericName: 'Chlordiazepoxide',
    brandNames: ['Librium'],
    category: 'benzodiazepine',
    medicationClass: 'Benzodiazepine',
    mechanism: 'Older benzodiazepine with calming and sedating effects.',
    confidence: 0.73,
    effectTags: sedFx,
    stateImpactTags: stBenzo,
  }),
  entry({
    id: 'temazepam',
    genericName: 'Temazepam',
    brandNames: ['Restoril'],
    category: 'benzodiazepine',
    medicationClass: 'Benzodiazepine',
    mechanism: 'Often used for sleep onset or maintenance support in prescribed anxiety/sleep plans.',
    confidence: 0.76,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'anxiety_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'oxazepam',
    genericName: 'Oxazepam',
    brandNames: ['Serax'],
    category: 'benzodiazepine',
    medicationClass: 'Benzodiazepine',
    mechanism: 'Intermediate benzodiazepine used for anxiety symptom support.',
    confidence: 0.73,
    effectTags: sedFx,
    stateImpactTags: stBenzo,
  }),
  entry({
    id: 'zolpidem',
    genericName: 'Zolpidem',
    brandNames: ['Ambien', 'Edluar'],
    category: 'sleep_aid',
    medicationClass: 'Non-benzodiazepine sleep medication',
    mechanism: 'Targets sleep-wake receptors; may shorten sleep onset with next-day grogginess risk for some.',
    confidence: 0.8,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context', 'training_readiness'],
  }),
  entry({
    id: 'eszopiclone',
    genericName: 'Eszopiclone',
    brandNames: ['Lunesta'],
    category: 'sleep_aid',
    medicationClass: 'Non-benzodiazepine sleep medication',
    mechanism: 'Sleep medication that may alter sleep continuity and morning alertness.',
    confidence: 0.79,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'zaleplon',
    genericName: 'Zaleplon',
    brandNames: ['Sonata'],
    category: 'sleep_aid',
    medicationClass: 'Non-benzodiazepine sleep medication',
    mechanism: 'Very short-acting sleep onset support for some prescribed plans.',
    confidence: 0.76,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'suvorexant',
    genericName: 'Suvorexant',
    brandNames: ['Belsomra'],
    category: 'sleep_aid',
    medicationClass: 'Orexin antagonist sleep medication',
    mechanism: 'Blocks wake-promoting orexin pathways; may support sleep maintenance with variable next-day effects.',
    confidence: 0.74,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'ramelteon',
    genericName: 'Ramelteon',
    brandNames: ['Rozerem'],
    category: 'sleep_aid',
    medicationClass: 'Melatonin receptor agonist (prescription)',
    mechanism: 'Targets melatonin receptors to support sleep timing signals.',
    confidence: 0.74,
    effectTags: ['sleep_relevant', 'sedation_relevant'],
    stateImpactTags: ['sleep_interpretation'],
  }),
  entry({
    id: 'quetiapine',
    genericName: 'Quetiapine',
    brandNames: ['Seroquel'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Dopamine and serotonin receptor effects; sedating for many people and used in several psychiatric plans.',
    confidence: 0.72,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'olanzapine',
    genericName: 'Olanzapine',
    brandNames: ['Zyprexa'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Broad receptor activity; may influence mood, sedation, appetite, and metabolic context.',
    confidence: 0.72,
    effectTags: [...apFx, 'appetite_relevant'],
    stateImpactTags: [...stAP, 'appetite_context'],
  }),
  entry({
    id: 'risperidone',
    genericName: 'Risperidone',
    brandNames: ['Risperdal'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Dopamine and serotonin antagonism used across several psychiatric indications.',
    confidence: 0.72,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'aripiprazole',
    genericName: 'Aripiprazole',
    brandNames: ['Abilify'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic (partial agonist)',
    mechanism: 'Dopamine stabilizing partial agonism; may affect mood, energy, and restlessness differently than sedating antipsychotics.',
    confidence: 0.73,
    effectTags: [...moodSleep, 'activation_relevant'],
    stateImpactTags: ['mood_context', 'sleep_interpretation', 'training_readiness'],
  }),
  entry({
    id: 'lurasidone',
    genericName: 'Lurasidone',
    brandNames: ['Latuda'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Used in bipolar depression and schizophrenia-related plans; sedation varies.',
    confidence: 0.71,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'ziprasidone',
    genericName: 'Ziprasidone',
    brandNames: ['Geodon'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Antipsychotic with activating or sedating profiles depending on individual response.',
    confidence: 0.7,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'paliperidone',
    genericName: 'Paliperidone',
    brandNames: ['Invega'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Active metabolite-related antipsychotic used in schizophrenia and mood-disorder plans.',
    confidence: 0.71,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'clozapine',
    genericName: 'Clozapine',
    brandNames: ['Clozaril'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Complex receptor profile; often reserved for specific clinical monitoring protocols.',
    confidence: 0.68,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'brexpiprazole',
    genericName: 'Brexpiprazole',
    brandNames: ['Rexulti'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Partial agonist activity used as adjunct in some depression plans.',
    confidence: 0.7,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'lithium',
    genericName: 'Lithium',
    brandNames: [],
    matchAliases: ['Lithium carbonate'],
    category: 'mood_stabilizer',
    medicationClass: 'Mood stabilizer',
    mechanism: 'Mood-stabilizing salt used in bipolar-related plans; narrow therapeutic monitoring is typical in clinical care.',
    confidence: 0.76,
    effectTags: ['mood_relevant', 'fatigue_relevant', 'hydration_relevant'],
    stateImpactTags: ['mood_context', 'fatigue_context', 'hydration_context'],
  }),
  entry({
    id: 'divalproex',
    genericName: 'Divalproex',
    brandNames: ['Depakote'],
    category: 'mood_stabilizer',
    medicationClass: 'Anticonvulsant / mood stabilizer',
    mechanism: 'Valproate-related compound used for seizure, migraine, and mood stabilization.',
    confidence: 0.74,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'valproic_acid',
    genericName: 'Valproic acid',
    brandNames: ['Depakene'],
    category: 'mood_stabilizer',
    medicationClass: 'Anticonvulsant / mood stabilizer',
    mechanism: 'Related to divalproex; used in mood and seizure disorders.',
    confidence: 0.73,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'carbamazepine',
    genericName: 'Carbamazepine',
    brandNames: ['Tegretol'],
    category: 'mood_stabilizer',
    medicationClass: 'Anticonvulsant / mood stabilizer',
    mechanism: 'Sodium channel modulation used for seizure and some mood-stabilization plans.',
    confidence: 0.73,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'oxcarbazepine',
    genericName: 'Oxcarbazepine',
    brandNames: ['Trileptal'],
    category: 'mood_stabilizer',
    medicationClass: 'Anticonvulsant / mood stabilizer',
    mechanism: 'Related to carbamazepine; used in seizure and some mood-support contexts.',
    confidence: 0.72,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'topiramate',
    genericName: 'Topiramate',
    brandNames: ['Topamax'],
    category: 'anticonvulsant',
    medicationClass: 'Anticonvulsant',
    mechanism: 'Multiple mechanisms; sometimes used for migraine prevention or mood-related adjunct plans.',
    confidence: 0.71,
    effectTags: [...moodSleep, 'fatigue_relevant'],
    stateImpactTags: [...stMS, 'recovery_interpretation'],
  }),
  entry({
    id: 'methylphenidate',
    genericName: 'Methylphenidate',
    brandNames: ['Ritalin', 'Concerta', 'Daytrana'],
    category: 'stimulant',
    medicationClass: 'ADHD stimulant',
    mechanism: 'Increases dopamine and norepinephrine availability; may improve focus with appetite and sleep timing effects.',
    confidence: 0.8,
    effectTags: stimFx,
    stateImpactTags: stStim,
  }),
  entry({
    id: 'dexmethylphenidate',
    genericName: 'Dexmethylphenidate',
    brandNames: ['Focalin'],
    category: 'stimulant',
    medicationClass: 'ADHD stimulant',
    mechanism: 'Stimulant enantiomer related to methylphenidate with similar vigilance and sleep-interaction considerations.',
    confidence: 0.78,
    effectTags: stimFx,
    stateImpactTags: stStim,
  }),
  entry({
    id: 'mixed_amphetamine_salts',
    genericName: 'Mixed amphetamine salts',
    brandNames: ['Adderall'],
    category: 'stimulant',
    medicationClass: 'ADHD stimulant',
    mechanism: 'Stimulant combination that may affect alertness, appetite, and sleep if taken late in the day.',
    confidence: 0.79,
    effectTags: stimFx,
    stateImpactTags: stStim,
  }),
  entry({
    id: 'lisdexamfetamine',
    genericName: 'Lisdexamfetamine',
    brandNames: ['Vyvanse'],
    category: 'stimulant',
    medicationClass: 'ADHD stimulant',
    mechanism: 'Longer-acting stimulant prodrug; still interacts with sleep timing and appetite for many users.',
    confidence: 0.79,
    effectTags: stimFx,
    stateImpactTags: stStim,
  }),
  entry({
    id: 'atomoxetine',
    genericName: 'Atomoxetine',
    brandNames: ['Strattera'],
    category: 'adhd_non_stimulant',
    medicationClass: 'SNRI-like ADHD medication',
    mechanism: 'Norepinephrine reuptake inhibition for ADHD-related attention patterns without stimulant classification.',
    confidence: 0.77,
    effectTags: [...moodSleep, 'fatigue_relevant'],
    stateImpactTags: ['mood_context', 'fatigue_context', 'training_readiness'],
  }),
  entry({
    id: 'guanfacine_er',
    genericName: 'Guanfacine',
    brandNames: ['Intuniv'],
    matchAliases: ['Guanfacine ER'],
    category: 'adhd_non_stimulant',
    medicationClass: 'Alpha-2 agonist',
    mechanism: 'May reduce hyperactivity and impulsivity patterns; sedation possible especially when starting.',
    confidence: 0.74,
    effectTags: sedFx,
    stateImpactTags: ['mood_context', 'sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'clonidine_er',
    genericName: 'Clonidine',
    brandNames: ['Kapvay'],
    matchAliases: ['Clonidine ER'],
    category: 'adhd_non_stimulant',
    medicationClass: 'Alpha-2 agonist',
    mechanism: 'Calming autonomic effects; sedation and blood-pressure-related context may matter for alertness.',
    confidence: 0.73,
    effectTags: [...sedFx, 'heart_rate_relevant'],
    stateImpactTags: ['sleep_interpretation', 'heart_rate_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'hydroxyzine',
    genericName: 'Hydroxyzine',
    brandNames: ['Vistaril', 'Atarax'],
    category: 'anxiolytic',
    medicationClass: 'Antihistamine with sedating effects',
    mechanism: 'Histamine blockade can produce sedation sometimes used for anxiety or sleep support.',
    confidence: 0.76,
    effectTags: sedFx,
    stateImpactTags: stBenzo,
  }),
  entry({
    id: 'pregabalin',
    genericName: 'Pregabalin',
    brandNames: ['Lyrica'],
    category: 'anticonvulsant',
    medicationClass: 'Gabapentinoid',
    mechanism: 'Calcium channel modulation; may calm nerve hyperexcitability with sedation or dizziness context.',
    confidence: 0.74,
    effectTags: [...moodAnx, 'pain_masking_relevant', 'fatigue_relevant'],
    stateImpactTags: ['anxiety_interpretation', 'pain_perception', 'fatigue_context'],
  }),
  entry({
    id: 'propranolol',
    genericName: 'Propranolol',
    brandNames: ['Inderal'],
    category: 'beta_blocker',
    medicationClass: 'Beta blocker',
    mechanism: 'Reduces sympathetic tone; sometimes used for physical anxiety symptoms and may influence heart rate interpretation.',
    confidence: 0.78,
    effectTags: ['heart_rate_relevant', 'anxiety_context', 'fatigue_relevant'],
    stateImpactTags: ['heart_rate_interpretation', 'anxiety_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'agomelatine',
    genericName: 'Agomelatine',
    brandNames: [],
    category: 'antidepressant',
    medicationClass: 'Melatonergic antidepressant',
    mechanism: 'Melatonin receptor agonism and serotonin antagonism; may affect sleep-wake timing and mood.',
    confidence: 0.7,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'maprotiline',
    genericName: 'Maprotiline',
    brandNames: [],
    category: 'tricyclic',
    medicationClass: 'Tetracyclic antidepressant',
    mechanism: 'Older antidepressant class with noradrenergic emphasis and sedation potential.',
    confidence: 0.68,
    effectTags: sedFx,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'diphenhydramine',
    genericName: 'Diphenhydramine',
    brandNames: ['Benadryl'],
    category: 'sleep_aid',
    medicationClass: 'Sedating antihistamine',
    mechanism: 'Histamine blockade causes sedation; sometimes used for short-term sleep support without prescription.',
    confidence: 0.72,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context', 'training_readiness'],
  }),
  entry({
    id: 'doxylamine',
    genericName: 'Doxylamine',
    brandNames: ['Unisom'],
    category: 'sleep_aid',
    medicationClass: 'Sedating antihistamine',
    mechanism: 'Sedating antihistamine sometimes used for sleep onset support.',
    confidence: 0.71,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'cariprazine',
    genericName: 'Cariprazine',
    brandNames: ['Vraylar'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Dopamine partial agonism used in schizophrenia and bipolar depression-related plans.',
    confidence: 0.69,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'asenapine',
    genericName: 'Asenapine',
    brandNames: ['Saphris'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Sublingual antipsychotic used in bipolar and schizophrenia-related care.',
    confidence: 0.68,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'iloperidone',
    genericName: 'Iloperidone',
    brandNames: ['Fanapt'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Dopamine and serotonin receptor effects used in schizophrenia-related plans.',
    confidence: 0.67,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'serdexmethylphenidate',
    genericName: 'Serdexmethylphenidate',
    brandNames: [],
    category: 'stimulant',
    medicationClass: 'ADHD stimulant',
    mechanism:
      'Stimulant agent used in some ADHD combination products; products may pair multiple agents—labels should match what you take.',
    confidence: 0.7,
    effectTags: stimFx,
    stateImpactTags: stStim,
  }),
  entry({
    id: 'esketamine',
    genericName: 'Esketamine',
    brandNames: ['Spravato'],
    category: 'antidepressant',
    medicationClass: 'NMDA-targeting antidepressant therapy',
    mechanism: 'Used in supervised treatment protocols for difficult-to-treat depression plans; sedation and dissociation context may matter the same day.',
    confidence: 0.65,
    effectTags: [...moodSleep, 'sedation_relevant'],
    stateImpactTags: ['mood_context', 'sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'trimipramine',
    genericName: 'Trimipramine',
    brandNames: ['Surmontil'],
    category: 'tricyclic',
    medicationClass: 'Tricyclic antidepressant',
    mechanism: 'Sedating tricyclic sometimes used for depression or insomnia-related plans.',
    confidence: 0.7,
    effectTags: sedFx,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'phenelzine',
    genericName: 'Phenelzine',
    brandNames: ['Nardil'],
    category: 'maoi',
    medicationClass: 'MAOI',
    mechanism:
      'Older antidepressant class; dietary counseling and clinician monitoring are typical parts of MAOI care plans.',
    confidence: 0.66,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'tranylcypromine',
    genericName: 'Tranylcypromine',
    brandNames: ['Parnate'],
    category: 'maoi',
    medicationClass: 'MAOI',
    mechanism: 'Irreversible MAO inhibition used in some depression plans under monitoring.',
    confidence: 0.65,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'isocarboxazid',
    genericName: 'Isocarboxazid',
    brandNames: ['Marplan'],
    category: 'maoi',
    medicationClass: 'MAOI',
    mechanism: 'MAOI antidepressant with legacy use in treatment-resistant depression contexts.',
    confidence: 0.64,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'selegiline',
    genericName: 'Selegiline',
    brandNames: ['Emsam'],
    category: 'antidepressant',
    medicationClass: 'MAO-B selective agent',
    mechanism: 'Used in Parkinson care and transdermal depression plans with formulation-dependent restrictions.',
    confidence: 0.65,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'midazolam',
    genericName: 'Midazolam',
    brandNames: ['Versed'],
    category: 'benzodiazepine',
    medicationClass: 'Benzodiazepine',
    mechanism: 'Short-acting benzodiazepine with strong sedation; sometimes used in procedural or acute care contexts.',
    confidence: 0.72,
    effectTags: sedFx,
    stateImpactTags: stBenzo,
  }),
  entry({
    id: 'triazolam',
    genericName: 'Triazolam',
    brandNames: ['Halcion'],
    category: 'sleep_aid',
    medicationClass: 'Benzodiazepine sleep medication',
    mechanism: 'Very short-acting benzodiazepine sometimes prescribed for sleep onset support.',
    confidence: 0.74,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context', 'anxiety_interpretation'],
  }),
  entry({
    id: 'haloperidol',
    genericName: 'Haloperidol',
    brandNames: ['Haldol'],
    category: 'antipsychotic',
    medicationClass: 'Typical antipsychotic',
    mechanism: 'Dopamine-blocking antipsychotic used across several psychiatric and acute agitation plans.',
    confidence: 0.7,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'fluphenazine',
    genericName: 'Fluphenazine',
    brandNames: ['Prolixin'],
    category: 'antipsychotic',
    medicationClass: 'Typical antipsychotic',
    mechanism: 'Older antipsychotic available in oral and long-acting depot forms in some regions.',
    confidence: 0.68,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'chlorpromazine',
    genericName: 'Chlorpromazine',
    brandNames: ['Thorazine'],
    category: 'antipsychotic',
    medicationClass: 'Typical antipsychotic',
    mechanism: 'Phenothiazine antipsychotic with broad receptor effects and sedation for many people.',
    confidence: 0.67,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'perphenazine',
    genericName: 'Perphenazine',
    brandNames: ['Trilafon'],
    category: 'antipsychotic',
    medicationClass: 'Typical antipsychotic',
    mechanism: 'Phenothiazine antipsychotic used in schizophrenia-related care plans.',
    confidence: 0.66,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'loxapine',
    genericName: 'Loxapine',
    brandNames: ['Adasuve'],
    category: 'antipsychotic',
    medicationClass: 'Typical antipsychotic',
    mechanism: 'Dibenzoxazepine antipsychotic with inhaled formulation options in some acute care contexts.',
    confidence: 0.66,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'molindone',
    genericName: 'Molindone',
    brandNames: ['Moban'],
    category: 'antipsychotic',
    medicationClass: 'Typical antipsychotic',
    mechanism: 'Older antipsychotic used less commonly; sedation and movement-effect patterns vary.',
    confidence: 0.62,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'modafinil',
    genericName: 'Modafinil',
    brandNames: ['Provigil'],
    category: 'stimulant',
    medicationClass: 'Wake-promoting agent',
    mechanism: 'Promotes wakefulness in narcolepsy and related plans; may influence alertness and sleep timing.',
    confidence: 0.76,
    effectTags: [...stimFx, 'training_readiness_relevant'],
    stateImpactTags: stStim,
  }),
  entry({
    id: 'armodafinil',
    genericName: 'Armodafinil',
    brandNames: ['Nuvigil'],
    category: 'stimulant',
    medicationClass: 'Wake-promoting agent',
    mechanism: 'Longer half-life enantiomer-related wakefulness support compared with modafinil for some users.',
    confidence: 0.75,
    effectTags: [...stimFx, 'training_readiness_relevant'],
    stateImpactTags: stStim,
  }),
  entry({
    id: 'solriamfetol',
    genericName: 'Solriamfetol',
    brandNames: ['Sunosi'],
    category: 'stimulant',
    medicationClass: 'Wake-promoting agent',
    mechanism: 'Dopamine/norepinephrine reuptake inhibition used for excessive daytime sleepiness in some sleep disorder plans.',
    confidence: 0.72,
    effectTags: [...stimFx, 'training_readiness_relevant'],
    stateImpactTags: stStim,
  }),
  entry({
    id: 'pitolisant',
    genericName: 'Pitolisant',
    brandNames: ['Wakix'],
    category: 'stimulant',
    medicationClass: 'Wake-promoting agent',
    mechanism: 'Histamine-related wakefulness support used in narcolepsy-related care in some regions.',
    confidence: 0.68,
    effectTags: [...stimFx, 'fatigue_relevant'],
    stateImpactTags: ['fatigue_context', 'sleep_interpretation', 'training_readiness'],
  }),
  entry({
    id: 'daridorexant',
    genericName: 'Daridorexant',
    brandNames: ['Quviviq'],
    category: 'sleep_aid',
    medicationClass: 'Orexin antagonist sleep medication',
    mechanism: 'Blocks orexin pathways to support sleep with variable next-day alertness effects.',
    confidence: 0.72,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'lemborexant',
    genericName: 'Lemborexant',
    brandNames: ['Dayvigo'],
    category: 'sleep_aid',
    medicationClass: 'Orexin antagonist sleep medication',
    mechanism: 'Orexin antagonist used for insomnia-related sleep plans; next-day sedation varies.',
    confidence: 0.72,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'metoprolol',
    genericName: 'Metoprolol',
    brandNames: ['Lopressor', 'Toprol XL'],
    category: 'beta_blocker',
    medicationClass: 'Beta blocker',
    mechanism: 'Reduces heart workload; sometimes used for physical anxiety symptoms under clinician guidance.',
    confidence: 0.76,
    effectTags: ['heart_rate_relevant', 'anxiety_context', 'fatigue_relevant'],
    stateImpactTags: ['heart_rate_interpretation', 'anxiety_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'atenolol',
    genericName: 'Atenolol',
    brandNames: ['Tenormin'],
    category: 'beta_blocker',
    medicationClass: 'Beta blocker',
    mechanism: 'Cardioselective beta blocker that may blunt physical stress responses for some users.',
    confidence: 0.74,
    effectTags: ['heart_rate_relevant', 'anxiety_context', 'fatigue_relevant'],
    stateImpactTags: ['heart_rate_interpretation', 'anxiety_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'bisoprolol',
    genericName: 'Bisoprolol',
    brandNames: ['Zebeta'],
    category: 'beta_blocker',
    medicationClass: 'Beta blocker',
    mechanism: 'Beta blocker used for blood pressure and heart rate management with calming physical symptom overlap for some.',
    confidence: 0.73,
    effectTags: ['heart_rate_relevant', 'fatigue_relevant'],
    stateImpactTags: ['heart_rate_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'prazosin',
    genericName: 'Prazosin',
    brandNames: ['Minipress'],
    category: 'alpha_blocker',
    medicationClass: 'Alpha-1 blocker',
    mechanism: 'Blood-pressure-related alpha blockade; sometimes used for nightmare-related sleep disturbance in trauma-informed plans.',
    confidence: 0.7,
    effectTags: [...sedFx, 'heart_rate_relevant'],
    stateImpactTags: ['sleep_interpretation', 'heart_rate_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'cyproheptadine',
    genericName: 'Cyproheptadine',
    brandNames: ['Periactin'],
    category: 'anxiolytic',
    medicationClass: 'Antihistamine with sedating effects',
    mechanism: 'Histamine blockade can produce sedation and appetite stimulation for some users.',
    confidence: 0.7,
    effectTags: [...sedFx, 'appetite_relevant'],
    stateImpactTags: ['sleep_interpretation', 'fatigue_context', 'appetite_context'],
  }),
  entry({
    id: 'lumateperone',
    genericName: 'Lumateperone',
    brandNames: ['Caplyta'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Serotonin receptor modulation used in schizophrenia and bipolar depression-related plans.',
    confidence: 0.69,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'pimavanserin',
    genericName: 'Pimavanserin',
    brandNames: ['Nuplazid'],
    category: 'antipsychotic',
    medicationClass: 'Atypical antipsychotic',
    mechanism: 'Serotonin inverse agonism used in Parkinson-related psychosis plans when prescribed.',
    confidence: 0.66,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'viloxazine',
    genericName: 'Viloxazine',
    brandNames: ['Qelbree'],
    category: 'adhd_non_stimulant',
    medicationClass: 'ADHD medication',
    mechanism: 'Norepinephrine-related modulation used for ADHD symptom patterns in some pediatric and adult plans.',
    confidence: 0.72,
    effectTags: [...moodSleep, 'activation_relevant'],
    stateImpactTags: ['mood_context', 'sleep_interpretation', 'training_readiness'],
  }),
  entry({
    id: 'protriptyline',
    genericName: 'Protriptyline',
    brandNames: ['Vivactil'],
    category: 'tricyclic',
    medicationClass: 'Tricyclic antidepressant',
    mechanism: 'Tricyclic with more activating profile for some users versus sedating tricyclics.',
    confidence: 0.68,
    effectTags: [...moodSleep, 'activation_relevant'],
    stateImpactTags: stMS,
  }),
  entry({
    id: 'amoxapine',
    genericName: 'Amoxapine',
    brandNames: [],
    category: 'tricyclic',
    medicationClass: 'Tricyclic antidepressant',
    mechanism: 'Tricyclic-related compound with dopamine activity overlap in its metabolites for some users.',
    confidence: 0.65,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'trifluoperazine',
    genericName: 'Trifluoperazine',
    brandNames: ['Stelazine'],
    category: 'antipsychotic',
    medicationClass: 'Typical antipsychotic',
    mechanism: 'Phenothiazine antipsychotic used historically for schizophrenia-related symptom patterns.',
    confidence: 0.66,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'thiothixene',
    genericName: 'Thiothixene',
    brandNames: ['Navane'],
    category: 'antipsychotic',
    medicationClass: 'Typical antipsychotic',
    mechanism: 'Thioxanthene antipsychotic with sedation profiles that vary by individual.',
    confidence: 0.65,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'mesoridazine',
    genericName: 'Mesoridazine',
    brandNames: ['Serentil'],
    category: 'antipsychotic',
    medicationClass: 'Typical antipsychotic',
    mechanism: 'Phenothiazine antipsychotic used less commonly in contemporary practice.',
    confidence: 0.62,
    effectTags: apFx,
    stateImpactTags: stAP,
  }),
  entry({
    id: 'ropinirole',
    genericName: 'Ropinirole',
    brandNames: ['Requip'],
    category: 'sleep_aid',
    medicationClass: 'Dopamine agonist',
    mechanism: 'Dopamine agonist used for restless legs and Parkinson-related plans; evening dosing may relate to sleep timing.',
    confidence: 0.72,
    effectTags: [...sedFx, 'fatigue_relevant'],
    stateImpactTags: ['sleep_interpretation', 'fatigue_context', 'mood_context'],
  }),
  entry({
    id: 'pramipexole',
    genericName: 'Pramipexole',
    brandNames: ['Mirapex'],
    category: 'sleep_aid',
    medicationClass: 'Dopamine agonist',
    mechanism: 'Dopamine agonist used for restless legs syndrome and Parkinson-related plans with sedation overlap for some users.',
    confidence: 0.72,
    effectTags: [...sedFx, 'mood_relevant'],
    stateImpactTags: ['sleep_interpretation', 'fatigue_context', 'mood_context'],
  }),
  entry({
    id: 'rotigotine',
    genericName: 'Rotigotine',
    brandNames: ['Neupro'],
    category: 'sleep_aid',
    medicationClass: 'Dopamine agonist',
    mechanism: 'Transdermal dopamine agonist used in restless legs and Parkinson-related symptom plans.',
    confidence: 0.71,
    effectTags: [...sedFx, 'fatigue_relevant'],
    stateImpactTags: ['sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'amantadine',
    genericName: 'Amantadine',
    brandNames: ['Gocovri', 'Osmolex ER'],
    category: 'neurology_adjunct',
    medicationClass: 'Glutamate-modulating agent',
    mechanism: 'Originally antiviral; used in Parkinson plans and sometimes adjunct depression contexts with activating or dizzying profiles.',
    confidence: 0.68,
    effectTags: [...moodSleep, 'activation_relevant'],
    stateImpactTags: stMS,
  }),
  entry({
    id: 'tiagabine',
    genericName: 'Tiagabine',
    brandNames: ['Gabitril'],
    category: 'anticonvulsant',
    medicationClass: 'Anticonvulsant',
    mechanism: 'GABA reuptake modulation used for seizure plans; sedation may overlap with sleep timing.',
    confidence: 0.68,
    effectTags: sedFx,
    stateImpactTags: ['sleep_interpretation', 'fatigue_context'],
  }),
  entry({
    id: 'zonisamide',
    genericName: 'Zonisamide',
    brandNames: ['Zonegran'],
    category: 'anticonvulsant',
    medicationClass: 'Anticonvulsant',
    mechanism: 'Anticonvulsant used for seizure and sometimes mood-adjunct plans; sedation varies.',
    confidence: 0.68,
    effectTags: moodSleep,
    stateImpactTags: stMS,
  }),
  entry({
    id: 'benztropine',
    genericName: 'Benztropine',
    brandNames: ['Cogentin'],
    category: 'movement_adjunct',
    medicationClass: 'Anticholinergic',
    mechanism: 'Anticholinergic medication sometimes used for movement side-effect support in psychiatric plans.',
    confidence: 0.68,
    effectTags: ['fatigue_relevant', 'mood_relevant'],
    stateImpactTags: ['fatigue_context', 'mood_context'],
  }),
  entry({
    id: 'trihexyphenidyl',
    genericName: 'Trihexyphenidyl',
    brandNames: ['Artane'],
    category: 'movement_adjunct',
    medicationClass: 'Anticholinergic',
    mechanism: 'Anticholinergic agent sometimes used for movement-related medication effects under clinician monitoring.',
    confidence: 0.66,
    effectTags: ['fatigue_relevant', 'mood_relevant'],
    stateImpactTags: ['fatigue_context', 'mood_context'],
  }),
];

fs.writeFileSync(outPath, JSON.stringify(rows, null, 2), 'utf8');
console.log(`Wrote ${rows.length} entries to ${outPath}`);
